name:  Hellow our fair world!  World

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build executable
      run: make

    - name: Test executable
      run: ./main | grep -q "Hello world!" && echo "Test passed" || (echo "Test failed" && exit 1)
